### ISSUE TITLE
Не виводити водойми у яких approval="rejected"

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#10]
Наші користувачі додають водойми на мапу. 

Якщо якість інформації в них низька, ми їх відкидаємо і не виводимо. 
За це відповідає поле ```approval``` воно має три значення:
1. approved
2. pending
3. rejected

Всі методи не повинні вибирати з бази даних записи у яких approval="rejected"
Як приклад можна подивитись водойму з id=377

Тип маркерів, що повертається має визначатись правами користувача. Тобто користувач, токен якого юзає андроїд, має мати таку роль, яка дозволяє йому бачити лише апрувнуті маркери. Такий собі policy scope.

**Comment by devrivne** [comment]
хм, якщо честно, та навышо тоды взагалы виводити навыть для адміна їх? Апрувнути можна в адмінці. ЧИ В НАС БУДЕ АНДРОЇД АПЛІКУХА ЯКА МОЖЕ СТВОРЮВАТИ/РЕДАГУВАТИ ЗАПИСИ?
Може просто всюди апрувнуті виводити? А апі я взагалі думав тільки дозвіл для читання для 100% користувачів.

**Comment by stal1n274** [comment]
> ЧИ В НАС БУДЕ АНДРОЇД АПЛІКУХА ЯКА МОЖЕ СТВОРЮВАТИ/РЕДАГУВАТИ ЗАПИСИ?
Так, користувачі прямо зі своїх телефонів будуть додавати нові рибні місця на мапу

> Може просто всюди апрувнуті виводити? 
Я за те, щоб виводити і approvedі ті що pending. Це як вікіпедія: користувач відразу бачить результат своєї роботи.
А вже пізніше адміністратори приймають рішення, залишити контент, чи реджекнути його

**Comment by ttp** [comment]
А чим це тоді відрізняється від простого видалення точки? Нащо тоді взагалі ці танці з статусом?
Не маркай як режектед а видаляй маркер, і буде тобі щастя, нащо в базі купа непотрібних маркерів?

**Comment by stal1n274** [comment]
Маркер після додавання має стан "в очікування на затвердження модератором", і модератор його або аппруває або реджектає.
В базі вони багато місця не займають, інформація не повинна втрачатись.

**Comment by ttp** [comment]
Яка інформація? Це навіть не історія, це нікому не потрібна точка яку ніхто не бачить. Ти за всю історію проекту хоч раз міняв режектад на апрувд?

**Comment by stal1n274** [comment]
Інформація про те, що там є рибне місце.
Ще не змінював, бо не так багато точок додали люди. 

Видаляти з таблички один запис погано, бо порушиться цілісність данних, адже там є посилання на записи в інших табличках. В такому разі потрібно видаляти всі записи пов'язані з поганим маркером.

**Comment by ttp** [comment]
>  бо порушиться цілісність данних, адже там є посилання на записи в інших табличках

конкретно називай таблички і поля де порушиться цілісність

> В такому разі потрібно видаляти всі записи пов'язані з поганим маркером.

так і треба

у вас в базі навіть індекса немає на поле ```approval``` і воно кожен раз фулскан робить, і це не відчутно бо точок поки ще мало

**Comment by stal1n274** [comment]
Поки не реалізовано повне видалення маркеру і всієї пов'язаної з ним інформації — не виводити водойми у яких ```approval="rejected"```

**Comment by ttp** [comment]
Інструмент і так є, питання лише скільки кроків він вимагає.
1. Заходиш в галереї, видаляєш галерею
2. Заходиш в пости, видаляєш пост
3. Заходиш в маркери, видаляєш маркер

Тому я б сказав зробити зручніший інструмент

**Comment by stal1n274** [comment]
Погоджуюсь Тарасе, потрібно ще додати:
4. Заходиш в табличку markers_fishers, видаляєш всіх риб пов'язаних з водоймою
5. Знаходиш на файловій системі галерею, видаляєш всі фотографії і саму директорію

Тому поки в API пропоную не виводити водойми у яких approval="rejected"

А розробка засобу видалення непотрібних маркерів - це інша історія.

**Comment by ttp** [comment]
записи з markers_fishers точно видаляються автоматом
і думаю малюнки також видаляються автоматом при видалені галереї

**Comment by stal1n274** [comment]
Я перепрошую, але при яких умовах автоматично видаляються записи з бази markers_fishers?

**Comment by ttp** [comment]
в базі є форін кі який їх видаляє каскадом

**Comment by devrivne** [comment]
Мені розбиратись з правами для груп/юзерів чи просто не виводити в апі взагалі???

**Comment by stal1n274** [comment]
На мою думку для всіх користувачів, хто отримує доступ до API користуючись токеном android_user не виводити маркери у яких ```approval="rejected"```

**Comment by devrivne** [comment]
short/markers
markers
все фільтрується для не суперюзерів.
