### ISSUE TITLE
API: Додати URL водойми в http://api.rivnefish.com/markers/

### ISSUE THREAD

**Issue by lordmegamax** [rivnefish/rivnefish#11]
Це буде "Лінк на детальну інфу" з https://github.com/rivnefish/rivnefish_android/issues/3

**Comment by stal1n274** [comment]
Вибірка URL водойми з бази даних(домен звісно брати з конфігу):

```
SELECT       
     CONCAT('http://rivnefish.com/','lakes/',post_name,'/')
FROM       
     wp_posts p
JOIN
	 markers m ON p.ID=m.post_id
where       
    marker_id=113;
```

**Comment by devrivne** [comment]
що саме додати і куди? В маркер додати якесь поле, з силкою на водойму?

**Comment by devrivne** [comment]
Зараз маэмо помилку: Exception Value:	Raw query must include the primary key

Так як в мене БД не маэ, то я можу лише методом тика =)

Роблю те саме з маркерами, а далі треба змінити запит.
==Ось приклад== 
В запит добавив `marker_id`
InvalidQuery: Raw query must include the primary key

In [17]: data = Markers.objects.raw('SELECT `marker_id`,`name` FROM `markers` WHERE `marker_id`=4')

In [18]: data
Out[18]: <RawQuerySet: 'SELECT `marker_id`,`name` FROM `markers` WHERE `marker_id`=4'>

In [19]: list(data)
Out[19]: [<Markers_Deferred_address_approval_area_author_id184c12ca45060837694cb668782255bf: Городище>]

In [20]: list(data)[0]
Out[20]: <Markers_Deferred_address_approval_area_author_id184c12ca45060837694cb668782255bf: Городище>

In [21]: list(data)[0].name
Out[21]: u'\u0413\u043e\u0440\u043e\u0434\u0438\u0449\u0435'

**Comment by stal1n274** [comment]
ось вибірка, яка включає primary key

```
SELECT       
     m.marker_id,
     CONCAT('http://rivnefish.com/','lakes/',post_name,'/')
FROM       
     wp_posts p
JOIN
     markers m ON p.ID=m.post_id
where       
    marker_id=113;
```

**Comment by devrivne** [comment]
Робить

**Comment by lordmegamax** [comment]
Я не бачу жодних змін, який параметр URL передає для конкретного маркеру?

**Comment by stal1n274** [comment]
Параметр ```url```

**Comment by lordmegamax** [comment]
Тепер є, вчора не було
