### ISSUE TITLE
Обрати тему для сайту

### ISSUE THREAD

**Issue by ttp** [rivnefish/rivnefish#11]
обрати тут: http://themeforest.net/search?utf8=%E2%9C%93&term=&view=list&sort=sales&date=&category=site-templates&tags[]=bootstrap&tags[]=multipurpose&price_min=&price_max=&sales=&rating_min=

**Comment by stal1n274** [comment]
обрати тут: http://themeforest.net/search?utf8=%E2%9C%93&term=&view=list&sort=sales&date=&category=site-templates&tags[]=bootstrap&tags[]=multipurpose&price_min=&price_max=&sales=&rating_min=

**Comment by stal1n274** [comment]
Буду писати ті теми, які мені хоч чимось сподобались, щоб потім вибирати з-поміж них:

http://themeforest.net/item/abtheme-bootstrap-responsive-html5-template/12908128
http://themeforest.net/item/gatwick-responsive-multipurpose-template/10705567
http://themeforest.net/item/denver-responsive-multipurpose-template/10617365

**Comment by MasterSergius** [comment]
Може остання тема ок, а так то всі якісь не дуже надихаючі :)

**Comment by ttp** [comment]
мені щось жодна не сподобалась :neutral_face:

**Comment by stal1n274** [comment]
Дякую за ваші відгуки! Кладу руку на серце і пишу: в цьому списку немає жодної такої теми, від якої б захоплювало дух і хотілось би кидати в монітор 17 баксів. Але маємо те, що маємо і потрібно робити тяжкий вибір.

Можливо є ще якесь місце, де можна підібрати тему?

**Comment by ttp** [comment]
https://bootswatch.com/
https://wrapbootstrap.com/themes/blogs-magazines
Google: *bootstrap themes*

**Comment by stal1n274** [comment]
Хтось може подумати, що я друшляю, насправді я щодня в пошуках теми.
Ось наприклад дуже проста/крута тема(не підійде для нашого двигунця): https://rakh.im/practical/

**Comment by stal1n274** [comment]
Три ночі, а я нічого хорошого не знайшов..

**Comment by stal1n274** [comment]
Обираю: https://wrapbootstrap.com/theme/key-lime-parallax-blog-template-WB062D26M

**Comment by stal1n274** [comment]
Merged by https://github.com/rivnefish/rivnefish/issues/70
