### ISSUE TITLE
API: Додати валідацію номеру телефону

### ISSUE THREAD

**Issue by lordmegamax** [rivnefish/rivnefish#12]
Для поля contact в http://api.rivnefish.com/markers/{id}

https://github.com/rivnefish/rivnefish_android/issues/3#issuecomment-84022303

**Comment by stal1n274** [comment]
Мені потрібно щось робити в базі даних зі всіма номерами телефонів?

**Comment by lordmegamax** [comment]
Якщо ти можеш все конвертувати в ріалтаймі то ні, але якщо не можеш - тоді потрібно привести базу в нормальний стан і зробити валідацію при вводі нових номерів на сайті.

**Comment by stal1n274** [comment]
Напиши будь ласка правильний формат, я буду по-трішки оновлювати існуючі номери телефонів

**Comment by lordmegamax** [comment]
Конкретний формат не має значення, головне щоб він був постійно однаковий. Можна просто цифри 067123456 або навіть з +38 починати.

**Comment by stal1n274** [comment]
Всі номери телефонів в базі даних оновлено до єдиного формату: +380XXXXXXXXX

**Comment by devrivne** [comment]
Треба якийсь метод додавати?

**Comment by lordmegamax** [comment]
Треба валідація щоб юзер не міг ввести нічого крім коректно сформованого номеру "єдиного формату: +380XXXXXXXXX"

**Comment by stal1n274** [comment]
поки що користувачі не можуть вводити дані в базу використовуючи API
так що ніяких методів додавати не потрібно
всі номери телефонів поки будуть перевірятись особисто мною і відразу виправлятися

**Comment by lordmegamax** [comment]
Зробіть валідацію на формі вводу на сайті, інакше десь забудеш виправити і аплікуха впаде

**Comment by stal1n274** [comment]
Аллікуха буде падати саме коли користувач обере конкретну водойму?

**Comment by lordmegamax** [comment]
Так, якщо в цій водоймі номер не буде відповідати шаблону.

**Comment by stal1n274** [comment]
API тут ні до чого .

Поле в базі даних, в якому зберігається номер телефону це просто ```text```
Туди пишуть не лише номер телефону, але й як звати охоронця чи власника.

У нас водойми додаються в базу на даний момент лише через сайт: http://rivnefish.com/lakes/add-fish-place/

Щоб зробити валідацію введення, потрібно саме на сайті її реалізовувати. Я це бачу так, поле розбивати на два: номер телефону і текстова примітка. Давати користувачу конкретну форму для введення телефону і окремо текстову примітку. 
Ще тут є нюанс в тому, що контактних телефонів може бути декілька.

Тому я закриваю це issue тут.

**Comment by lordmegamax** [comment]
> Ще тут є нюанс в тому, що контактних телефонів може бути декілька.

Кнопочка + і внизу ще 2 поля телефону? А в API передавати масив?

**Comment by stal1n274** [comment]
Ми дані не передаємо в API, а просто записуємо в базу даних напряму
