### ISSUE TITLE
[API] Метод для пошуку водойм, де клює риба Х

### ISSUE THREAD

**Issue by lordmegamax** [rivnefish/rivnefish#123]
Метод по ID риби шукає всі водойми де можна спіймати цю рибу і повертає їх список.

**Comment by stal1n274** [comment]
Це вже є в API.
Ось приклад вибору риби "Чорний Амур" (id=15):
https://rivnefish.com/api/v1/places/for_map?fish%5Bfish%5D%5B%5D=15

В цьому методі є й інші параметри, як то вага риби та ін.
Це вже можна глянути інспектором на сайті - головна сторінка - "Фільтрувати водойми"

Це те що потрібно?

**Comment by stal1n274** [comment]
Закриваю це

Якщо будуть питання - сміло перевідкривайте
