### ISSUE TITLE
https

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#16]
Для наших користувачів потрібно реалізувати захищений спосіб авторизації на сайті.
Найкраще це робити через захищений протокол https і тут нас потрібен сертифікат. Зазвичай вони платні і вартують від 20 баксів в рік та вище.
Ось що я знайшов з халяви: 
1. https://www.startssl.com/ - обмеження в довжині ключа, дають безкоштовний на три роки.
2. https://cacert.org./ - трохи стрьомне
3. https://habrahabr.ru/post/257207/ - опис ще одного сервісу(китайського)

**Comment by ttp** [comment]
Я говорив про https://www.startssl.com/. Спробуй використати його.

**Comment by stal1n274** [comment]
Сертифікат для new.rivnefish.com готовенький, валідний до 2017-02-08
Надішлю тобі його листом, заінсталь на сервачку :kissing_closed_eyes:

**Comment by stal1n274** [comment]
На сертифікат матюкається файрфокс, всі інші браузери працюють з ним без проблем.
Потрібно ще з нього прибрати keyphrase.
