### ISSUE TITLE
Генерувати URL з результатами фільтрації водойм

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#20]
Дуже цікаве для мене питання: а чи можливо генерувати URL на результати пошуку? Щоб можна було ділитись з друзями результатами своїх пошуків і фільтрацій. Це теж пахне кіллер-фічею. Можна додати кнопку в самому низу форми фільтрації: "Згенерувати мені результат цього пошуку".

**Comment by ttp** [comment]
URL сторінки автоматично змінюється якщо ми міняємо параметри пошуку або рухаємо карту і може використовуватись щоб поділитись результатами пошуку.

Наприклад, платні водойми поблизу Львова де водиться карп: http://new.rivnefish.com/?permit[]=paid&time_to_fish=full_day&boat_usage=1&fish[fish][]=2&lat=49.859886796868594&lng=23.943563448242244&z=9

**Comment by stal1n274** [comment]
Все виглядає супер! Це так легко: знайти якісь цікаві місця і просто зкопіювати посилання в браузері. Мені дуже подобається.

Єдине зауваження: чи можливо якось уникнути символів % в URL? Наприклад писати там лише знаення латинецею(брати прямо з бази)

**Comment by ttp** [comment]
@stal1n274 Я не бачу ніяких % крім назви і там цього не уникнути ніяк, дай приклад де в тебе % і назву браузера/ос.

**Comment by stal1n274** [comment]
Круто, все ок
