### ISSUE TITLE
Нові місця не з'являються на мапі після додавання

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#21]
Якщо скористатись формою "Додати водойму", то відповідна сторінка створюється, але без поплавка на мапі. Ось приклад: http://new.rivnefish.com/places/place-563

Як відтворити:
1. На головній сторінці натиснути на кнопку "Додати водойму", або перейти відразу на цю сторінку: http://new.rivnefish.com/places/new
2. Поставити точку на карті внести будь-які дані в опис, натиснути кнопку "Додати"
3. Перевірити на головній сторінці, чи з'явилась точка на мапі.

**Comment by ttp** [comment]
Це не бага, точка в черзі на ревью, поки ти її в адмінці не зміниш вона на мапі не з"явиться.
