### ISSUE TITLE
Імпортувати звіти з основного сайту

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#22]
- [x] імпортувати текст
- [x] імпортувати фото в самому звіті
- ~~імпортувати галереї з Google Photos~~
- [x] мапінг коментарів на нові сторінки

**Comment by stal1n274** [comment]
Це неймовірно, але все рухається вперед! 
Я знайшов два баги і маю маленьке побажання.

1. Вертикальні фото всередині допису стискаються по висоті всіх інших фото
![image](https://cloud.githubusercontent.com/assets/5851581/18035057/17facbee-6d56-11e6-801f-f396bc53f1e0.png)

2. Шістнадцятої сторінки звітів не існує, підозрюю, що там якийсь дивний допис, який крешить всю сторінку: http://new.rivnefish.com/reports?page=16

3. Чи можна зробити відступи між фотографіями в галереї розміром в 4 пікселі?
![image](https://cloud.githubusercontent.com/assets/5851581/18035080/a341ac86-6d56-11e6-8db7-c0d2cb6c14ef.png)

4. Featured image зникає, якщо додати розширену інформацію про рибалку (як мінімум скільки і якої риби було зровлено)

**Comment by ttp** [comment]
@stal1n274 done
