### ISSUE TITLE
Панель керування: Тип рибалки

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#23]
Нам потрібно нова таблиця в базі даних, яка бути містити в собі типи рибалок. 
Кожен звіт з рибалки буде відноситись мінімум до однієї з цих категорій. Щоб потім можна було легко переглядати лише ту рибалку, яка цікавить користувача.
Ось які я пропоную створити типи рибалок:

- поплавок
- фідер
- карпфішинг
- спінінг
- літня мормишка
- нахлист
- зимня рибалка
- морська рибалка
- метод(воно ж спутнік, воно ж буде й класична донка)

**Comment by ttp** [comment]
@MasterSergius тут те саме що і з наживками, просто створиш окрему табличку і моделі, тобі після наживок має бути справ на 15хв зробити все те саме.

**Comment by ttp** [comment]
@stal1n274 перевір
