### ISSUE TITLE
Панель керування: наживки/насадки

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#24]
Нам потрібно мати нову таблицю в базі даних з визначеними насадками(наживками). При додаванні звіту з рибалку користувач буде мати змогу вибрати на що саме в нього клювала риба.
І ми будемо зв'язувати запис з таблиці "риби на водоймі" з цією новою таблицею "насадки"
Пропоную наповнити її такими значеннями:

- Хробак
- Опариш
- Мотиль
- Горох
- Кукурудза
- Зернові
- Картопля
- Мастирка
- Тісто
- Бойли солодкі
- Бойли кислі
- Бойли рибні
- Інші насадки для білої риби
- Живець
- Жаба
- Блешня коливна
- Блешня обертова 
- Силікон
- Поролон
- Воблер
- Попер
- Блешня відвісна
- Балансир
- Мормишка безмотилка

**Comment by ttp** [comment]
@MasterSergius це має бути задачка на годинку часу, додати нову сторінку в адмінку для редагування насадок

**Comment by ttp** [comment]
@stal1n274 перевір

**Comment by stal1n274** [comment]
Всі насадки додались в базу, все ок.
Обрати їх при створенні звіту поки що не можливо.

Цікаво, чи можна було б розділити насадки по категоріям?
Наприклад: 
якщо тип рибалки "Фідер", то обрати насадку можна лише для білої риби.
якщо тип рибалки "Спінінг",  то обрати насадку можна лише для хижої риби.

**Comment by ttp** [comment]
давай не ускладнювати поки
до звіту це поки відношення не має і буде робитись коли буде робитись можливість додати пійману рибу, якщо все ок, закривай
