### ISSUE TITLE
Додавання звіту: позначати/вибирати місце рибалки на мапі

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#25]
При створенні звіту ми маємо прив'язувати його до якоїсь водойми.
- [x] Користувач може обрати водойму скориставшись пошуком в текстовому полі
- [x] Поряд з полем "Пошук водойм" має бути кнопка з іконкою мапи. При натисканні на цю кнопку з'являється мапа, на які позначені всі водойм з нашої бази даних.
- [x] Центрувати мапу потрібно згідно обраної точки.
- [x] Користувач може обрати місце на карті. Якщо користувач клікає на існуючу точку карти то звіт зв'язується з цією водоймою і в поле "пошук водойми" підставляється назва водойми.
- ~~Якщо користувач клікає на пусте місце карти то звіт зв'язується з НОВОЮ водоймою, яка додається в базу з текстом, який написано в звіті і рибою, яка додається в звіт (якщо додається). Назва для цієї нової точки береться з Google Map API найближчого населеного пункту від цієї координати.~~ (винести в окреме ішю)

**Comment by ttp** [comment]
@stal1n274 перевір і поміть зроблені пункти, останній пункт винеси в окремий тікет
якщо все ок, можеш закривати

**Comment by stal1n274** [comment]
Все виглядадає супер гуд! :thumbsup:

Дрібні зауваження:
1. Чи можна перекласти на рідну мову підказку "Please enter 1 or more characters" ?
2. Може кнопу ,"Додати" варто перейменувати в "Зберегти" або "Опублікувати" або "Додати звіт"?
3. Думаю, що варто перейменувати "Заголовок звіту" на "Назва звіту", що скажете?
4. Я трішки не розібрався з підказами над полями (напр. ліворуч від "Заголовок звіту")

**Comment by ttp** [comment]
Вітя, ти знову за своє із дрібними покращеннями :). Тут лише 1 треба пофіксати.
А решта взагалі ніяк не відноситься до цієї таски. Всі навіть дрібні покращення описуй до того як таска буде робитись, глянь опис таски по звіту яку ти ж і робив, свій мокап, і прочитай тепер свої зауваження.

**Comment by ttp** [comment]
Пофіксив мову
