### ISSUE TITLE
Імпортувати місця з основного сайту

### ISSUE THREAD

**Issue by ttp** [rivnefish/rivnefish#3]
- [x] імпортувати маркери

**Comment by stal1n274** [comment]
Чи є якийсь шанс імпортувати підписи до фото?

**Comment by stal1n274** [comment]
Водойми, для яких я писав цілі есе в більшості своїй мали таку приємну оку штуку як [Featured Image](https://en.support.wordpress.com/featured-images/) - це картинка в заголовку статті.
Саме ця картинка береться фейсбуком і іншими соціальними мережами в якості іконки до розшареного урла.
Приклади таких статей, щоб було зрозуміло про що йде мова:
* http://rivnefish.com/lakes/zhalyanka/
* http://rivnefish.com/lakes/gorodishhe-bereznivske/
* http://rivnefish.com/lakes/bochanicya/

Ось як виглядає таке розшарене посилання з Featured Image в фейсбуці:
![image](https://cloud.githubusercontent.com/assets/5851581/11624609/b30df858-9cdd-11e5-9aa9-903265eef822.png)
А ось так виглядає стаття без такого зображення:
![image](https://cloud.githubusercontent.com/assets/5851581/11624630/ce8c90a8-9cdd-11e5-88bc-acc0c31385bb.png)

Чи можна мати такий же функціонал і імпортувати наявні малюнки туди?
дякую

**Comment by ttp** [comment]
можна, але Вітя, збери одразу всі ріквайрменти, бо мені доводиться всі дані імпортувати по новій, дампити і заливати на сервак, а це 2-3Г малюнків і купа часу щоб зробити сам імпорт

**Comment by stal1n274** [comment]
зрозумів
будь ласка, не запускай поки що імпорт водойм, я перегляну те, що вже імпортнулось і можливо напишу якісь ще побажання :)
дякую!

**Comment by stal1n274** [comment]
1. Пропоную або витягнути alt для малюнків з бази даних, або зробити його таким же, як і підпис. А ще краще його просто згенерувати: 
фото %place_name% рибалка

**Comment by stal1n274** [comment]
2. Було б вельми добре витягнути з бази даних **Title** і **Description** сторінки

**Comment by ttp** [comment]
а нащо тобі ще title? title це ж назва водойми

**Comment by stal1n274** [comment]
Неа, у нас тайтл може відрізнятись від назви водойми. Зараз спробую знати кілька таких прикладів.
http://rivnefish.com/lakes/hotyn/
http://rivnefish.com/lakes/hrushiv/
http://rivnefish.com/lakes/yavorivskyj-karjer/

І якщо в описах водойм це не так кидається в очі, то для звітів з рибалки - це критичне поле(це я про майбутній імпорт)

**Comment by ttp** [comment]
До чого тут звіт до місця. Ти заходиш на сторінку опису місця, чому там має бути інший заголовок?

**Comment by stal1n274** [comment]
1. В селі Хотин є річка Горинь, є величезна стариця цієї ріки(старе русло заповнене водою), а є ще кар'єри, де колись видобували глинозем. Місце на маркері - Хотин, а тайтл сторінки вказує конкретно про кар'єри.
2. В Грушеві розміщується одне з найбільших водосховищ Львівської області. Місце називається Грушів, а в тайтлі уточнення, що це рибалка саме на завадівському водосхвищі. 
І так далі

Головна моя ідея була така: на карті розміщувати лаконічні й прості назви рибних місць, а вже в розширеному описі водойми писати гарну велику назву.
Це для пошуковий систем критично, по якій саме назві показувати користувачу інформацію. Якщо людина шукає "Рибалка Завадівське водосховище" або "Рибалка Грушів" - щоб їй показувало найперше посилання на наш сайт. Бо буде збіг як не по тайтлу сторінки, так по її вмісту. Ок?

А чому я приплів сюди звіти про рибалку, бо там тайтл дуже важливий і щоб ми його обовязково витягнули без змін.

**Comment by stal1n274** [comment]
"Примітка по оплаті" не імпортнулась. Поле 'paid_fish' в базі даних вордпресу.

Це є одним з головних полів про умови вилову риби на ставку, там міститься короткий текст з умовами вилову риби.
Саме це поле виводиться зараз в вордпресі на поплавку поряд з рибою і телефоном
як на мене, то варто виводити саме його, а не числові значення за день і добу, бо бувають різні нюанси, наприклад: "30 грн коштує кожна вудка", чи "риболовля триває лише до першої години".

**Comment by ttp** [comment]
@stal1n274 done
