### ISSUE TITLE
Slug генерувати в URL

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#30]
[https://en.wikipedia.org/wiki/Semantic_URL#Slug](https://en.wikipedia.org/wiki/Semantic_URL#Slug)
Ця штука необхідна для того, щоб краще індексувався контент і потім знаходився в інтернеті.
Як це працює можна подивитись на приклад на реддіті:  https://www.reddit.com/r/ukraina/comments/4ka646/%D0%B4%D0%BE%D0%B1%D1%80%D0%BE_%D0%B8_%D0%B7%D0%BB%D0%BE_%D1%81%D1%85%D0%BB%D0%B5%D1%81%D1%82%D0%BD%D1%83%D0%BB%D0%B8%D1%81%D1%8C_%D0%B2_%D0%BD%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B5%D0%B2%D0%B5/
або деінде: https://fidobank.ua/news/492_nu_prosto_ohuet_teper.html 
Можемо обговорити корисність такої штуки взагалі.

**Comment by stal1n274** [comment]
Вирішили: для кожного місця генерувати унікальний ID і далі записувати назву водойми латинецею. 

Приклад
new.rivnefish.com/places/274/lebedynka

**Comment by ttp** [comment]
done
