### ISSUE TITLE
Не відображається кирилиця на маркерах

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#32]
Прийшов я сьогодні до тещі в гості до тещі і спробував відкрити наш сайт. А мені тут кубики якісь малюються.

Простий рибалка не буде ні в чому розбиратись і щось налаштовувати, він просто ніколи в житті більше не зайде на цей сайт.

![rivnefish_no_c](https://cloud.githubusercontent.com/assets/5851581/15635347/44297e44-25e5-11e6-975a-4715aaf4c6f7.JPG)
Тут старенький комп'ютер:
Opera 12.17 (1863), Windows XP, win32

**Comment by ttp** [comment]
Викинь свій старенький пк, або простав сам кодування в утф8, якщо вона сама не вміє

**Comment by stal1n274** [comment]
Не можу викинути, бо це комп не мій, а моєї тещі.

Повторюю: прості люди не будуть ніякого кодування ніде ставити, вони навіть слова такого не знають.

Я ще перевірю на інших машинах і в разі чого повернемось сюди.
