### ISSUE TITLE
При перегляді деталей про водойму "Прилбичі" фотографії при збільшенні відображаються у зменшеному розмірі

### ISSUE THREAD

**Issue by belgeu** [rivnefish/rivnefish#33]
Кроки для відтворення:
-------------------------
1. Відкрити браузер, у адресну стрічку увести адресу ресурсу - [http://rivnefish.com](http://rivnefish.com)
2. Знайти на карті водойму "Прилбичі" або скористатись фільтром "Відобразити список водойм" (праворуч на межі екрану) та відфільтрувати водойму по назві ввівши "Прилбичі" у стрічку фільтру.
3. Клікнути на будь-яку із зображених фото.

Фактичний результат:
-------------------------
Фотографії при кліканні на них ("збільшити") відображаються у зменшеному розмірі (53х9 пікселів). Гіперпосилання не вірне та містить зайві символи у частині посилання /s**20**0/.
`https://lh5.googleusercontent.com/-ef1zpkRhbzA/UEpfnh5EidI/AAAAAAAAOvg/UbNi0hIf8cU/s200/20%2B07%2B12%2B17%25D0%25BA%25D0%25B3.jpg`

Очікуваний результат:
-------------------------
Фотографії відображаються у збільшеному розмірі (989х659 пікселів). Гіперпосилання виправлене та містить /s0/:
`https://lh5.googleusercontent.com/-ef1zpkRhbzA/UEpfnh5EidI/AAAAAAAAOvg/UbNi0hIf8cU/s0/20%2B07%2B12%2B17%25D0%25BA%25D0%25B3.jpg`

**Comment by stal1n274** [comment]
Fixed.
More photographes have been added.
