### ISSUE TITLE
API методи: розробити аналогічні, що використовуються зараз

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#34]
Нам потрібно, щоб через API мобільні аплікації брали інформацію з нашої бази даних.
В перший чергу потрібно реалізувати ті методи, які вже працюють на старому сайті:

```
http://api.rivnefish.com/markers/
http://api.rivnefish.com/lastchanges/
http://api.rivnefish.com/markers-fishes/?marker=\(id)
http://api.rivnefish.com/fishes/
```

Коли це буде готово, розробимо нові методи (не лише get, але ще i post, та трошечки delete...)
Все обговоримо з нашими розробниками мобільних додаткиів

**Comment by MasterSergius** [comment]
Як побачити приклад відповідей з того старого сайту? Потрібна авторизація

**Comment by stal1n274** [comment]
Так, звісно, що можна.
Все тобі підготую.

**Comment by MasterSergius** [comment]
Уже краще. Ще б тепер знати що робити, коли ключі в json в старому апі відрізняються від нових? Чи треба робити якусь додаткову обробку для сумісності чи ні? А також де почерпати саму інфу про методти? Наприклад, lastchanges - взагалі нічого мені не говорить, що то за таймстемп і звідки він береться.

**Comment by stal1n274** [comment]
Всі методи описані ось тут: https://github.com/rivnefish/rivnefish_api/wiki/Methods

**Comment by MasterSergius** [comment]
Виконано - https://github.com/rivnefish/rivnefish/pull/35
Можна закривати ішью?

**Comment by MasterSergius** [comment]
А тепер можна закривати ішью? Хочеться закрити толком хоч одне, щоб було таке собі почуття завершеності :)

**Comment by stal1n274** [comment]
Ще не можна закривати, бо:

- Потрібно методи описати тут: https://github.com/rivnefish/rivnefish/wiki/API-methods (це зроби ти)

- Потрібно методи протестувати (напиши мені як)

**Comment by MasterSergius** [comment]
Методи описав. Як протестувати? Ну, хіба робити руками селекти і порівнювати з отриманими json-ами. Відповідно, перевірити чи такі поля є у json:
**places:**  id, name, lat, lng, area, depth_avg, depth_max, permit, time_to_fish, price_24h, price_day_only, price_notes, boat_usage, address, description, notes, conveniences, contact_phone, contact_name, rating_avg, rating_votes, photos, places_fishes

**fish:** id, name, name_latin, name_eng, name_folk, slug, predator, redbook, description, icon_url

**Comment by stal1n274** [comment]
:+1:
