### ISSUE TITLE
Не можливо зареєструватись, якщо в повному імені введено знак пробілу

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#37]
Відкриваємо сторінку для реєстрації: http://new.rivnefish.com/users/sign_up
В полі "* Повне ім'я" вводимо: Vasia Pupkin
далі правильно заповнюємо всі інші поля і клацаємо на кнопку "Зареєструватись"

отримуємо помилку:
"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

**Comment by MasterSergius** [comment]
Цікаво чим відрізняється наразі дев від проду, бо на моїй дев тачці пропустило нормально

**Comment by ttp** [comment]
Це пов"язано з моїми ресторами бд з дампу, це не бага.
