### ISSUE TITLE
Вставляти форматований текст в редактор без фону

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#39]
Для того, щоб перенести всі звіти з форуму на сайт потрібно їх звідти покопіювати. Але на форумі завжди в тексту є голубий фон. Якщо його копіювати і вставляти в існуючий редактор звітів, то виходить не гарно геть. Потрібно на ходу прибирати фон.

У мене все вийшло в тестовому режимі, я лише підключив плагін paste до нашого редактору tinymce:
```
<!DOCTYPE html>
<html>
<head>
  <script src="http://cdn.tinymce.com/4/tinymce.min.js"></script>
  <script>
  tinymce.init({
    selector:'textarea',
    plugins : 'paste'
  });</script>
</head>
<body>
  <textarea>Easy (and free!) You should check out our premium features.</textarea>
</body>
</html>
```

**Comment by stal1n274** [comment]
resolved with commit: 76a5320c35d702c327ec84b1d69559bc2d032c67
pull request:  https://github.com/rivnefish/rivnefish/pull/41
integrated in build:

**Comment by ttp** [comment]
Deployed
