### ISSUE TITLE
Фільтри водойм на мапі

### ISSUE THREAD

**Issue by ttp** [rivnefish/rivnefish#4]
- [x] Додати панель для фільтрів що відкриває всі фільтри
- [x] Фільтрувати за *Умови рибалки* (безкоштовно, платно, ...)
- [x] Фільтрувати за *Коли можна рибалити*
- [x] Фільтрувати за наявною рибою і мін. вагою риби
- [x] Фільтрація по *величині водойми*

~~Фільтрувати водойми *в залежності від дистанції*, від якої ведеться пошук~~ (не бачу в цьому сенсу, оскільки візуально і так видно відстань від будь-якої точки

**Comment by stal1n274** [comment]
Чи можна буде фільтрувати водойми за областями, районами? 
Мені дуже подобається ось така реалізація: http://libruk.in.ua/map.html

**Comment by stal1n274** [comment]
Доповнюю:
1. Фільтрація по *величині водойми* (ми можемо закодувати величини, напр. до 3 Га це мальнеьке, до 10 Га це середнє, до 100 Га велике, понад 100 ВЕЛИЧЕЗНЕ, понад 1000 безкрайнє)) (понад 1000 гектарів займає нетішенське водосховище, яке більше за місто Рівне, так-то))
2. Фільтрувати водойми *в залежності від дистанції*, від якої ведеться пошук - це просто killer fature!
3. Фільтрувати не лише по рибі, а й *по її величні* :) Наприклад, я хочу рибалити лише там, де клює карась більше як півкіло.

**Comment by stal1n274** [comment]
Тарасе, все виглядає дуже гарно і відразу зрозумілим як користуватись! :+1: 

Фільтрування зовсім не таке, яке я собі уявляв :)
Я думав, що ми будемо отримувати список водойм. Але нехай буде так, побачимо, як це сприймуть наші користувачі.

Зауваження та проханнячка:

1. Чи можна додати інтуітивно очікувану кнопку закриття фільтру в правому верхньому куточку?
![image](https://cloud.githubusercontent.com/assets/5851581/13030456/87da0ebc-d2b4-11e5-9796-d60b9e207b61.png)

2. Чи можна "умови рибалки" зробити випадаючим списком? Якщо я розраховую на безкоштовну рибалку мене далі не цікавлять платники і запрєткі :)
Цим самим ми зекономимо додатково купу місця.

3. Пропоную перейменувати:
"Коли можна рибалити"
->
"Дозволена нічна рибалка " - і відразу поряд місце для галочки.

4. Дуже не вистачає поля фільтрації по назві. Це супер крута штука, для швидкого пошуку потрібного місця, якщо знаєш як воно зветься, але не знаєш де воно є. Так як це працює зараз на нашому сайті мені дуже подобається! (коли можна знайти місце навіть по другому слові в назві)

5. Я надіюсь шукати по величні риби також можна буде?

6. Дуже цікаве для мене питання: а чи можливо генерувати URL на результати пошуку? Щоб можна було ділитись з друзями результатами своїх пошуків і фільтрацій. Це теж пахне кіллер-фічею. Можна додати кнопку "згенерувати мені результат цього пошуку". Можемо винести це як окреме issue

**Comment by ttp** [comment]
> Я думав, що ми будемо отримувати список водойм.

Я не знаю чи є сенс в списку відфільтрованих водойм, якщо на мапі все лишається як було. Поверне воно тобі 300 безкоштовних місць списком, і що з ними робити? Ти ж не будеш по кожному з них клікати, щоб взнати де вони знаходяться?

> Дуже не вистачає поля фільтрації по назві

Тут треба подумати, оскільки та фільтрація, що в нас зараз на продакшені, це фільтрація по показаних водоймах, коли ми їх відфільтруємо, то деякі водойми пропадуть і пошук по назві піде вже лише по відфільтрованих водоймах, що може трохи конфузити. Загалом це все треба подумати як правильно зробити, обговоримо офлайн.

---

> Про вагу риби треба ще покумекати як то реалізувати бо наскільки я зрозумів, там зараз працює логічне "або".

Якщо задав вагу, то воно пофільтрує водойми де є риба >= заданої ваги, якщо ще вибрав рибу, то де є ще така риба. І от по рибі вже йде логічне *або*, водойми де є хоч якась риба із заданих у фільтрі.

Приклади:
1. `Риба: Карп, Карась` - Водойми де є Капр **або** Карась
2. `Риба: Карп, Карась; Вага: 1кг` - Водойми де є *Капр або Карась*, і *Карп або Карась* має вагу `>= 1кг`
3. `Вага: 1кг` - Водойми де хоч якась риба має вагу `>= 1кг`

---

> чи можливо генерувати URL на результати пошуку?

Можливо, винось в окреме ішю

**Comment by stal1n274** [comment]
Ось як я приблизно собі уявляю фільтр водоймі по рибі:
![image](https://cloud.githubusercontent.com/assets/5851581/13201498/cddf882e-d87c-11e5-80d2-c607c041c54b.png)

Коли в нас буде більше даних, то в цій же формі додамо колонки по значення "наскільки реально тут впіймати ту рибу?"

**Comment by ttp** [comment]
> Ось як я приблизно собі уявляю фільтр водоймі по рибі

Блін, та хто оце буде таким страждати і вводити на кожну рибу свою вагу. Мені те що зараз простішим виглядає.

**Comment by ttp** [comment]
Зроблено
