### ISSUE TITLE
API: Додати можливість отримувати всі дані одним запитом без пейджинга

### ISSUE THREAD

**Issue by lordmegamax** [rivnefish/rivnefish#4]
Маю на увазі окремо для кожного запиту:
    "countries": "http://api.rivnefish.com/countries/", 
    "regions": "http://api.rivnefish.com/regions/", 
    "districs": "http://api.rivnefish.com/districs/", 
    "fishes": "http://api.rivnefish.com/fishes/", 
    "markers": "http://api.rivnefish.com/markers/", 
    "markers-fishes": "http://api.rivnefish.com/markers-fishes/", 
    "markers-log": "http://api.rivnefish.com/markers-log/", 
    "passports": "http://api.rivnefish.com/passports/"

**Comment by devrivne** [comment]
Реалізовано.
git pull + update !!!settings.py!!! В репозиторії дефолтний! кожен сам його розкоментовує і вносить правки/паролі/і тп.

**Comment by stal1n274** [comment]
Олексій, ти заливав на гіт якісь апдейти? 
Не бачу жодного нового комміту, останній був 9 січня

**Comment by devrivne** [comment]
settings.py.default
Там налаштування стоїть по параметру:  'PAGINATE_BY_PARAM': 'page_size',
#'PAGINATE_BY': 10,
    'PAGINATE_BY_PARAM': 'page_size',
    'UNICODE_JSON': 'true',
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework.filters.DjangoFilterBackend',
    ),
