### ISSUE TITLE
Редагувати URL Slug для звітів

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#45]
1. Додати в редактор адміністратора можливість редагувати Slug
2. Виключити можливість використання символу "/" в Slug URL

Приклад: http://new.rivnefish.com/reports/116/Bochanytsia-4%2F08%2F12---5%2F08%2F12-z-18-00-do-14-00 
Суміжне іш'ю: https://github.com/rivnefish/rivnefish/issues/30

**Comment by stal1n274** [comment]
потрібно ще виключити можливість використання символу " в Slug URL
приклад: http://new.rivnefish.com/reports/157/Horodyshche-bereznivske-%22Klova-dacha%22--09-05-2013

**Comment by ttp** [comment]
Проблема буле геть не в тому
