### ISSUE TITLE
Імпортовані кропнуті малюки поганої якості :(

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#46]
Особливо це добре видно по feature image.
Приклад: http://new.rivnefish.com/reports/334/Bochanytsia--25-26-07-2015

Ось тут можна порівняти:
https://rivnefish-photos.s3.eu-central-1.amazonaws.com/store/post/000/001/040/featured_image/post_thumb-e9b2b838ba34ac4790a1112dbef52f05.jpg
http://rivnefish.com/wp-content/uploads/2015/07/20150725_Fishing_Bochanytsia_0581-880x280.jpg

**Comment by stal1n274** [comment]
У мене таке враження, що ця проблема стосується лише feature image,
мені або не вистачає гостроти зору побачити різницю в простих малюнках, або її там немає:
https://rivnefish-photos.s3.eu-central-1.amazonaws.com/store/photo/000/000/465/photo/medium-4abba28294c7fbd973281fa40f2313b8.jpg
http://rivnefish.com/wp-content/blogs.dir/1/files/rybolovetskyj-stav-virlya/20150529_fishing_virlia_0091.jpg

**Comment by ttp** [comment]
Залий малюнки кращої якості для featured_image
