### ISSUE TITLE
Замінити календар в редакторі звітів

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#47]
Тим календарем, що є зараз, користуватись важко, воно не user friendly.
Будемо шукати кращий варіант.

**Comment by stal1n274** [comment]
Мені найбільше до вподоби ось такий варіант: http://jonthornton.github.io/Datepair.js/
(реалізація передостання знизу)

**Comment by stal1n274** [comment]
Щоб не створювати ще один баг: при редагуванні звіту з рибалку дані про дату рибалки не виводяться і їх постійно треба вводити заново.

**Comment by ttp** [comment]
Я відключив навігацію з клавіатури в поточному календарі, спробуй і скажи чи тобі ще реально потрібно його міняти.

**Comment by stal1n274** [comment]
Стало краще, але вводити час рибалки не зручно. Краще замінити, щоб можна було просто вводити скільки тривала рибалка двома кліками миші і тоді кінець виставлятиметься автоматично.
І навігацію клавіатури там теж вимкнути.

**Comment by stal1n274** [comment]
Ладно, лишаєм. 
Побачимо як відреагують користувачі.
