### ISSUE TITLE
API: Додати метод який повертає список зображень для маркера

### ISSUE THREAD

**Issue by lordmegamax** [rivnefish/rivnefish#5]
Потрібно по "gallery_id" повернути список зображень.

stal: фотографії завантажені на сервер і кожен маркер має лише посилання на айдішнік галереї, яка містить фото. Ось тут можна почитати: http://www.nextgen-gallery.com/help/

**Comment by devrivne** [comment]
Я можу вернути тыльки те, що э там, попередньо запихнувши все в список
    "photo_url1": "http://lh4.ggpht.com/_AlLFR-j5gDI/TSM-k-cBv0I/AAAAAAAAA1A/9mW0M4zCpd0/goringrad1.jpg", 
    "photo_url2": "http://lh6.ggpht.com/_AlLFR-j5gDI/TSM-lZv1XwI/AAAAAAAAA1I/P2ITPohq9SA/goringrad2.jpg", 
    "photo_url3": "http://lh6.ggpht.com/_AlLFR-j5gDI/TSM-lYxpkhI/AAAAAAAAA1Q/XkARJ-aOIv4/goringrad3.jpg", 
    "photo_url4": "http://lh6.ggpht.com/_AlLFR-j5gDI/TSM-uOHSDcI/AAAAAAAAA1Y/ls3fo9mrlro/goringrad4.jpg", 

"photos":[url1,ul2,url3,url4]

**Comment by stal1n274** [comment]
Тут потрібно діставати зовсім інші фотографії.

У нас є вордпрес, в якому інстальовано плагін NextGEN Gallery. Для кожної водойми створено окремий фотоальбом засобами цього плагіну. Поле markers.gallery_id мість айдішнік саме на потрібний фотоальбом до водойми, ось сюди він зсилаєьтся: wp_ngg_gallery.gid

Тобто маючи в базі даних посилання на альбом потрібно звідти діставати фотки.

Ось структура:

mysql> desc wp_ngg_gallery;
+----------------+--------------+------+-----+---------+----------------+
| Field          | Type         | Null | Key | Default | Extra          |
+----------------+--------------+------+-----+---------+----------------+
| gid            | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| name           | varchar(255) | NO   |     | NULL    |                |
| slug           | varchar(255) | NO   |     | NULL    |                |
| path           | mediumtext   | YES  |     | NULL    |                |
| title          | mediumtext   | YES  |     | NULL    |                |
| galdesc        | mediumtext   | YES  |     | NULL    |                |
| pageid         | bigint(20)   | NO   |     | 0       |                |
| previewpic     | bigint(20)   | NO   |     | 0       |                |
| author         | bigint(20)   | NO   |     | 0       |                |
| extras_post_id | bigint(20)   | NO   | MUL | 0       |                |
+----------------+--------------+------+-----+---------+----------------+
10 rows in set (0.00 sec)

mysql> desc wp_ngg_pictures;
+----------------+--------------+------+-----+---------------------+----------------+
| Field          | Type         | Null | Key | Default             | Extra          |
+----------------+--------------+------+-----+---------------------+----------------+
| pid            | bigint(20)   | NO   | PRI | NULL                | auto_increment |
| image_slug     | varchar(255) | NO   |     | NULL                |                |
| post_id        | bigint(20)   | NO   | MUL | 0                   |                |
| galleryid      | bigint(20)   | NO   |     | 0                   |                |
| filename       | varchar(255) | NO   |     | NULL                |                |
| description    | mediumtext   | YES  |     | NULL                |                |
| alttext        | mediumtext   | YES  |     | NULL                |                |
| imagedate      | datetime     | NO   |     | 0000-00-00 00:00:00 |                |
| exclude        | tinyint(4)   | YES  |     | 0                   |                |
| sortorder      | bigint(20)   | NO   |     | 0                   |                |
| meta_data      | longtext     | YES  |     | NULL                |                |
| extras_post_id | bigint(20)   | NO   | MUL | 0                   |                |
| updated_at     | bigint(20)   | YES  |     | NULL                |                |
+----------------+--------------+------+-----+---------------------+----------------+
13 rows in set (0.00 sec)

**Comment by stal1n274** [comment]
Ось добре видно, де знаходяться картинка для альбома №403:
mysql> select path from wp_ngg_gallery where gid=403;
+------------------------------------------+
| path                                     |
+------------------------------------------+
| wp-content/blogs.dir/1/files/penkivtsi_1 |
+------------------------------------------+
1 row in set (0.00 sec)

[offtop]як тут зробити код гарно читабельним?[/offtop]

**Comment by stal1n274** [comment]
Ось добре видно, де знаходяться картинки для водойми "Яворів" (вибірка на основні айдішніка маркеру):

SELECT
	g.path
FROM 
	wp_ngg_gallery g 
LEFT JOIN
    markers m ON g.gid=m.gallery_id
WHERE m.marker_id=474;

+--------------------------------------+
| path                                 |
+--------------------------------------+
| wp-content/blogs.dir/1/files/yavoriv |
+--------------------------------------+
1 row in set (0.00 sec)


[offtop]як тут зробити код гарно читабельним?[/offtop]

**Comment by devrivne** [comment]
Ясно. Пізніше трохи подумаю як це зробити.

**Comment by lordmegamax** [comment]
Або можна повертати його масивом одразу в  @GET("/markers/{marker_id}/")

**Comment by devrivne** [comment]
Давайте я поки посто добавлю якесь нове поле, наприклад photos
і в ньом ПОКИ ЩО захардкоджу список урлів на картинки
вийде photos: ['url1', 'url2','url3'....]  яке буде однаково для всіх маркерів.
А коли буде час напишу метод, який буде тягнути ці урли і підставляти для кожного маркера.

**Comment by devrivne** [comment]
Захардкодив поле `photos`

**Comment by stal1n274** [comment]
Дані на сервері з гітом синхронізовано.

Олексій, тримай нас вкурсі як там в тебе буде виходити доступитись до фоток на сервері, як треба буде якась допомога в чомусь, то відразу пиши

Успіхів тобі!

**Comment by devrivne** [comment]
Дайте запрос для витягування малюнків. Бо в мене база тільки для реста

**Comment by stal1n274** [comment]
Олексій, що ти маєш на увазі? Який запит чи база тобі потрібні?

**Comment by stal1n274** [comment]
Ось запит в базу даних, який повертає повний шлях до зображень маркера з айдішніком 474

```SELECT
	CONCAT('rivnefish.com/',g.path,'/',p.filename)
FROM
	wp_ngg_pictures p,
	wp_ngg_gallery g 
LEFT JOIN
	markers m ON g.gid=m.gallery_id
WHERE 
	p.galleryid=m.gallery_id
AND
	m.marker_id=474 ;
```

```
rivnefish.com/wp-content/blogs.dir/1/files/yavoriv/oz-0e7181a3c27069a8367faef889d6e068c978e357.jpg
rivnefish.com/wp-content/blogs.dir/1/files/yavoriv/img_2775-4f53f0ce7ec4f8be50be50692592c840928644e0.jpg
rivnefish.com/wp-content/blogs.dir/1/files/yavoriv/oz2-4e9036ed863a69996b372bc4f877de06bd593d7d.jpg
rivnefish.com/wp-content/blogs.dir/1/files/yavoriv/mostyk-44a98ecb191825e7b3d8e2c926354a44ad4e9336.jpg
```

**Comment by ttp** [comment]
1) Домен має братись з конфігу

2) Перепиши все на звичайні JOIN, не LEFT JOIN і порядок
```
...
FROM markers
JOIN gallery ON ...
JOIN pictures ON ...
```

3) у WHERE має лишитись лише ```m.marker_id=474```, решту умов перемістити в ON

**Comment by stal1n274** [comment]
Така квіря ок(хостнейм вже береться з конфігу, не звертайте уваги)?

```
SELECT
    CONCAT('http://rivnefish.com/',g.path,'/',p.filename)
FROM
    wp_ngg_pictures p
JOIN
    wp_ngg_gallery g ON g.gid=p.galleryid
JOIN
    markers m ON g.gid=m.gallery_id
WHERE
    m.marker_id=474 ;
```

**Comment by devrivne** [comment]
оновив
