### ISSUE TITLE
Числа після коми в площі водойми втрачаються

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#51]
Приклад: http://new.rivnefish.com/places/738/Zhytyn-dovhyi-stav
тут я вводив площу ставка 1.17 гектар

**Comment by stal1n274** [comment]
ойой!
ми окрулюємо всі коми, навіть в глибинах
це критичний баг: втрата даних

**Comment by ttp** [comment]
вони в нас в базі як int

**Comment by stal1n274** [comment]
терміново треба щось змінювати, бо для глибин це критично
