### ISSUE TITLE
Додавання водойми: не робити перевірку значень при не введені площі та глибин

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#52]
Якщо я не знаю глибини чи площі ставка, я маю мати можливість його додати на карту.

![image](https://cloud.githubusercontent.com/assets/5851581/19211899/1fd2f21e-8d50-11e6-8b71-f735c6866b73.png)

**Comment by stal1n274** [comment]
Після користування редактора водойм пропоную зняти взагалі всі перевірки.

**Comment by ttp** [comment]
поіменно будь ласка

**Comment by ttp** [comment]
fixed

**Comment by stal1n274** [comment]
Перевірки НЕ робити для наступних полів:

- Умови для відпочинку
- Умови рибалки
- Умови рибалки
- Коли можна рибалити
- Ціна за добу
- Ціна за світлу пору доби
- Примітка по оплаті
- Використання човна
- Площа водойми
- Середня глибина
- Максимальна глибина
- Адреса
- Ім'я контактної особи
- Телефон

Всі ці характеристики водойми мають бути опційними

**Comment by ttp** [comment]
вони і є опціональні, але 0 це не пусте поле, а некоректне значення, стри його і дасть зберегти
