### ISSUE TITLE
Адмінка: додати dropdown список користувачів для зміни автора допису

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#55]
Нам потрібно перенести всі звіти з нашого форуму в базу даних рівнефіш.
Я хочу зберегти авторів цих публікацій. Для цього потрібно:

Додати можливість вибирати автора допису адміну.

**Comment by ttp** [comment]
Винеси імпорт користувачів в окреме ішю, воно до вибору юзера як такого відношення не має
