### ISSUE TITLE
Імпорт користувачів форуму

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#56]
Нам потрібно:
- [x] Вибрати користувачів з бази даних форуму: дата реєстрації, ім'я користувача, пароль(?), дата останнього успішного логіну, унікальний номер.
- [ ] Імпортувати ці дані в базу даних рівнефіш

Суміжне іш'ю: https://github.com/rivnefish/rivnefish/issues/55

**Comment by ttp** [comment]
Я вважаю, що це ніяк не відноситься до блокерів, форум форумом, а сайт сайтом

**Comment by stal1n274** [comment]
Давай хоча б імпортнемо авторів звітів?
Якщо автор зареєстрований на форумі, то під звітом стоїть його підпис. Наприклад:
[forest]

**Comment by ttp** [comment]
@stal1n274 Ти це можеш зробити через адмінку

**Comment by stal1n274** [comment]
вибірки:

`fishmap_dev=> select r.created_by from posts p JOIN reports r ON p.postable_id=r.id  where content like '%[RIPsys]%' AND postable_type='Report';`

`fishmap_dev=> UPDATE reports AS r SET created_by=42 FROM posts AS p WHERE r.id=p.postable_id AND p.content like '%[RIPsys]%' AND p.postable_type='Report';`
