### ISSUE TITLE
Відсутні галереї з фотографіями в звітах з рибалки

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#58]
Наприклад:
http://rivnefish.com/blog/2016/07/24/basiv-kut-11/
http://new.rivnefish.com/reports/388/Basiv-Kut-v-raioni-Novoho-Dvora--24-07-16r-

http://rivnefish.com/blog/2016/09/12/tarnavka-5-09-6-09/
http://new.rivnefish.com/reports/393/Tarnavka-5-09-6-09

http://rivnefish.com/blog/2016/08/18/kryve/
http://new.rivnefish.com/reports/391/s-Kryve-FH-%22KLOVO%22--26-29-07-2016

**Comment by ttp** [comment]
Я більше нічого не буду імпортити, хочеш мігруй руками.
