### ISSUE TITLE
API: Створити token для доступу android клієнта.

### ISSUE THREAD

**Issue by lordmegamax** [rivnefish/rivnefish#6]
Must be read-only.

**Comment by devrivne** [comment]
Реалізовано. АПДЕЙТНІТЬ КОНФІГИ!

**Comment by stal1n274** [comment]
Згенерував токен для користувача android_user тут: http://api.rivnefish.com/admin/authtoken/token/

**Comment by lordmegamax** [comment]
403 Forbidden
Невже не можна просто сюди його скопіювати? Він же всеодно буде публічним...

**Comment by stal1n274** [comment]
Там отаке: a035641c7e58ddf8acd98acb1470f4205e22adcd

**Comment by ttp** [comment]
не постьте ніяких токенів в публічний доступ доки не буде вирішена проблема із правами доступу
Вітя, проапдейть токен на новий і скинь в приват

**Comment by stal1n274** [comment]
Коли я створював android_user то не давав йому жодних прав щось правити, видаляти чи додавати.
Але це необхідно протестувати.
Новий токен скинув на пошту.

**Comment by lordmegamax** [comment]
Токен досі не працює

GET http://api.rivnefish.com/markers/?format=json HTTP/1.1
Authorization: Token 7eeb7a212ШМАТОКВИРІЗАНОДЛЯБЕЗПЕКИee67
User-Agent: Dalvik/1.6.0 (Linux; U; Android 4.4.2; LG-LS980 Build/KOT49I.LS980ZVC)
Host: api.rivnefish.com
Connection: Keep-Alive
Accept-Encoding: gzip

**Comment by stal1n274** [comment]
перемагаючи простір і час - виконано.

1. Додано опцію в конфіг віртуал серверу
WSGIPassAuthorization On
2. Юзера додано в групу staff
