### ISSUE TITLE
Сторінка додавання водойми користувачами

### ISSUE THREAD

**Issue by ttp** [rivnefish/rivnefish#6]
- [x] Додавання водойми користувачем/гостем
- [x] Якщо це зареєстрований користувач то помітити це місце як додане цим користувачем.
- [x] ~~Додати в профайл користувача кількість доданих ним точок.~~ (додасться після створення профайлу)
- [x] Конфігурація додавання водойм гостями
- [x] Інформування листом про додану водойму

**Comment by stal1n274** [comment]
Чи можна зробити можливість додавання водойми гостями конфігурябельною?
Захотів - дозволив, захотів - вимкнув.

**Comment by ttp** [comment]
Можна

**Comment by stal1n274** [comment]
1. Опис

 Підказка виводиться як простий текст під формою
2. Риба

 чи можна заголовок зробити таким же, як й інші?
 чи можна трішки розширити поле для введення нотатки про кльов риби? не видно слова "хробака" 
3. Дозвіл рибалити

 чи можна застосувати такий же принцип як і тут: http://rivnefish.com/lakes/add-fish-place/ ?
 тобто лише коли обираємо "платно", тоді можна вводити ціну й контакти
 десь треба написати, що ціни в гривнях
4. Фотографії

 чи можна перекласти кнопку й напис поряд?
5. І чи можливо вводити площу водойми в гектарах?  Тому що це загальновживана міра одиниці площі водойм в нашій країні взагалі. Впевнений, що більшість людей навіть ари в гектари ніколи й не переведе.

**Comment by stal1n274** [comment]
Сергій, надихайся ось цієї формою:
http://rivnefish.com/lakes/add-fish-place/

Для користувача має бути доступно лише кілька елементів для заповення:
1. Назва
2. Місце на мапі (але тут підказка дуже в тему, спасибі Тарас!)
3. Опис рибалки
4. Умови рибалки

Всі інші поля для заповення показувати лише по кліку на кнопку "Розширена форма" (або інша назва).

**Comment by ttp** [comment]
Мені форма всеодно виглядає громіздкою, я пропоную обмежитись лише наступними полями:
1. Назва
2. Місце на мапі
3. Опис місця

А решту сховати в панелях, буде виглядати приблизно отак:
![selection_017](https://cloud.githubusercontent.com/assets/52537/12308000/759cc82e-ba4b-11e5-8d92-41816e3a3869.png)

Хто захоче, той розгорне і заповнить необхіндні поля.

**Comment by stal1n274** [comment]
Підтримую Тарас

**Comment by MasterSergius** [comment]
І що це значить? Мені знову треба братися за цю форму? Прошу зробити уточнення.

**Comment by ttp** [comment]
я вже все змінив, Вітя подивись і скажи чи можна ще щось покращити

**Comment by stal1n274** [comment]
Загалом все подобається!
Маю кілька дрібних зауважень:

1. Чи можна, щоб додаткові форми розкривались не лише по кліку по назві (напр. "Риба"), а по всій плашці?
2. Чи можна пересунути форму "Коли можна рибалити" на один рівень з "Умови оплати"?
3. Чи потрібно нам додавати адресу в поле "Контакт"? Я думаю, що пізніше ми реалізуємо автоматичне заповнення адреси на основі координат точки.
4. Ціни можуть бути від'ємними :) Не порядок
5. Пропоную все-таки валідувати номер телефону згідно
https://github.com/rivnefish/rivnefish_android/issues/14
https://github.com/rivnefish/rivnefish_wordpress/issues/94
номер телефону має записуватись в базу даних нормалізовано. щоб було зручно по ньому відразу клацати в додатку і телефонувати
6. Площу водойми краще вводити в гектарах, наш народ мало оперує арами при підрахунку площі
7. В "Додаткова інформація" додати поле "Дуже важлива коротка примітка!"
8. Можливо перемістити ціну за добу й за світлу поре доби в "Додаткова інформація"?

**Comment by ttp** [comment]
> Чи можна пересунути форму "Коли можна рибалити" на один рівень з "Умови оплати"?

Воно зав"язане на умову і з"являться динамічно, а тому нехай все з"являється під ним. Або прибрати цю "динамічність" і показувати завжди все.

> Чи потрібно нам додавати адресу в поле "Контакт"? 

Потрібно, ми ще не знаєм чи це можна зробити інакше.

> В "Додаткова інформація" додати поле "Дуже важлива коротка примітка!"

Всі примітки пиши в опис, не треба плодити купу незрозумілих полів.

> Можливо перемістити ціну за добу й за світлу поре доби в "Додаткова інформація"?

Знову внести нотку хаосу :smiley: . Це відноситься до оплати, якого дива його переміщувати в інший блок? Я проти.

> Площу водойми краще вводити в гектарах, наш народ мало оперує арами при підрахунку площі

Зараз в тебе в базі всі дані в арах, і тому форма також в арах, заведи окремий ішю на те щоб перевести ари в гектари в базі.

**Comment by stal1n274** [comment]
Зрозумів Тарас
Зі всім погоджуюсь

**Comment by ttp** [comment]
Вчора ще трохи погрався, додав деякі айтеми, потестуй

**Comment by stal1n274** [comment]
Як вважаєш, може так буде краще?

"Ціна за добу" -> "Ціна за добу (грн)"
"Ціна за світлу пору доби" -> "Ціна за світлу пору доби (грн)"

**Comment by stal1n274** [comment]
Важливий момент!
Після додання водойми потрібно формувати імейл на групу модераторів, з посиланням на сторінку редагування цієї водойми в адмінці.

**Comment by ttp** [comment]
Вітя, що тут очікується? можна закривати?

**Comment by stal1n274** [comment]
1. В "Додаткова інформація" додати поле "Дуже важлива коротка примітка!"
2. "Ціна за добу" -> "Ціна за добу (грн)"
3. "Ціна за світлу пору доби" -> "Ціна за світлу пору доби (грн)"

**Comment by ttp** [comment]
А "Дуже важлива коротка примітка!" це не те саме що в нас вже є як "notes"?

**Comment by stal1n274** [comment]
Так, це і є notes. Вище я пояснив навіщо воно. Можемо колегіально вирішити чи потрібне.

**Comment by ttp** [comment]
ну то воно вже є, я ще одне не додаю
