### ISSUE TITLE
Стрічка новин: змінити сортування по часу риболовлі

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#61]
На даний момент стрічки новин сортують по часу додавання допису.
Сортувати ж потрібно по часу, коли стартувала риболовля.

Приклади:
http://new.rivnefish.com/places/392/netishin-vodoskhovishhe-khaes/reports
http://new.rivnefish.com/reports

Якщо початок риболовлі при написані звітів не вказується, пропоную його прописувати рівним даті створення звіту.

**Comment by ttp** [comment]
Дублікат?

**Comment by stal1n274** [comment]
так точно
