### ISSUE TITLE
Виводити рандомне featured image для звітів без фоток

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#64]
Світлину брати з галереї водойми

**Comment by ttp** [comment]
шта?

**Comment by stal1n274** [comment]
Якщо користувач не додав фотографій у звіт до риболовлі, то я пропоную ставити цьому звіту featured image з галереї водойми.
Тільки, щоб для кожного такого звіту це була випадкова фотографія з галереї водойми, тоді буде гарно відображатись список "Звіти з цього місця" (кожен звіт з різною фоточкою)
![image](https://cloud.githubusercontent.com/assets/5851581/21555376/5a60d76e-ce20-11e6-91a6-ea6cd427c37b.png)

**Comment by ttp** [comment]
Це буде вводити користувача в оману що це фотки із звіту.
