### ISSUE TITLE
Реєстрація нових користувачів

### ISSUE THREAD

**Issue by ttp** [rivnefish/rivnefish#7]
Додати реєстрацію звичайних користувачів

**Comment by stal1n274** [comment]
Будемо реєструвати по логіну/паролю?

Дані про користувачів будемо зберігати всі в одній табличці?

**Comment by ttp** [comment]
1. по імейлу/паролю,
2. так, в одній табличці

**Comment by ttp** [comment]
Реєстрація має працювати

**Comment by stal1n274** [comment]
Мої пропозиції (можемо обговорити):

1. Користувачі нехай вводять собі нікнейм вже після реєстрації? Можна зробити поле ```Повне ім'я``` не обов'язковим.

2. Чому відображається пошта, а не ім'я?
![image](https://cloud.githubusercontent.com/assets/5851581/11451974/7ce8e552-95e0-11e5-9ae7-68af1b1daef5.png)

3. При підтвердженні реєстрації, до користувача звертаються не по імені, а по назві email:

``Ласкаво просимо stal1n@york.rv.ua!``
``Ви можете підтвердити вашу адресу перейшовши за посиланням нижче:``
``Підтвердити мій аккаунт``

4. На сторінці з реєстрацією: Запам"ятати мене -> Запам'ятати мене

5. Чи можна додати текст біля соціальних кнопок: "Увійти за допомогою"

6. Після натискання кнопки "Зареєструватись" в новому вікні фокус стоїть на формі з імейлом, користувачу потрібно буде повертатись до введення ім'я. Тут або фокус поставити на саму першу форму, або зробити її необов'язковою.

7. Користувач авторизувався на сайті. Дивиться мапу, клікає на різні маркери. Вирішив на черговому натиснути "Деталі/Коментарі >>>". І тут йому вилазить повідомлення "Вхід успішний".
Чи можливо це повідомлення показувати відразу після успішної аутентифікації? Бо така його поява трохи з запізненням :)

**Comment by ttp** [comment]
Виправив все крім **1.**, перевір. Обов'язковість імені можна обговорити вживу разом.

**Comment by stal1n274** [comment]
Чудово, дякую! :+1:

**Comment by stal1n274** [comment]
Може нам варто в цю ж форму додати захист від ботів у вигляді ось такої рекапчі?

![image](https://cloud.githubusercontent.com/assets/5851581/13075296/b9c7b9ce-d4b2-11e5-8bdc-2f38fb13e740.png)
