### ISSUE TITLE
API: Додати параметр в http://api.rivnefish.com/markers/

### ISSUE THREAD

**Issue by lordmegamax** [rivnefish/rivnefish#7]
Є необхідність діставати тільки часткову інформацію по всіх маркера. Повна інформація дуже велика і на GPRS тормоза нереальні.

Можливо додати щось на зразок ?output_type=short?

В основному потрібні тільки:
"marker_id": 1,
"name": "Рівне",
"address": "місто Рівне",
"lat": 50.619617,
"lng": 26.251379,
"photo_url1": "http://lh5.ggpht.com/_Al...jpg",
"photo_url2": null,
"photo_url3": null,
"photo_url4": null,

**Comment by devrivne** [comment]
можна по іншому урлу, наприклад short/markers

**Comment by lordmegamax** [comment]
Без різниці, головне щоб повертались мінімальна кількість необхідних даних
маркерів.

2015-03-06 15:32 GMT+02:00 devrivne <notifications@github.com>:

> можна по іншому урлу, наприклад short/markers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rivnefish/rivnefish/issues/7#issuecomment-77558651>.
>



-- 


*Best regards,Max MelnychukAndroid developer, freelancer.*

*Skype: lordmegamaxtel: +38 068 541-74-58*
