### ISSUE TITLE
Макет головного сайту

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#70]
Дизайнер розробив нам макет для сайту.
Тут я викладу прототипи ключових сторінку і відразу свої коментарі до них:

1. Головна сторінка
![image](https://cloud.githubusercontent.com/assets/5851581/20144792/75168e6a-a6a6-11e6-99e8-fbdd0223f65b.png)

- [x] Ми тут порадились і вирішили змінити наш слоган на  "Поділись риболовлею!"

- [x] Якщо я кожного дня користуюсь ресурсом, кожного дня бачити кнопку "спробувати" мене буде напрягати. Думаю, що варто показувати мапу відразу.

- [x] "Останні звіти" - тут може бути якесь лайно. Тіпок з тапках, надітих на шкарпетки з цигаркою в зубах триматиме за очі щуку, з якої йде кров, і два слова в описи "Басік сьодня".
Тому пропоную виводити не останні три звіти, а найкращі звіті.

- [x] У цих трьох звітах є опис. Пропоную там виводити title та description сторінки. 

- [x] "Архів звітів" перейменувати в "Всі звіти"

2. Головна сторінка з мапою
![image](https://cloud.githubusercontent.com/assets/5851581/20145200/d28cd148-a6a7-11e6-9353-f768f14cdd7e.png)

- [x] Мапа з рибними місцями - наша головна фіча. Пропоную її виводити на весь екран.

3. Сторінка зі звітами
![image](https://cloud.githubusercontent.com/assets/5851581/20145256/0f64f50a-a6a8-11e6-8729-566752b1627e.png)

- [x] Біля кожного звіту має бути головна картинка, рейтинг кльову, зловлена риба і коли відбувалась рибалки

- [x] Пропоную і картинку і весь текст зробити клікабельним 

- [x] На сторінці по висоті має поміщатись не манше як три звіти, і щоб між ними в майбутньому можна було розмістити якийсь банер, чи оголошення

Взагалі ось приклад, які елементи звітів повинна включати ця сторінка: http://new.rivnefish.com/reports?page=12

4. Сторінка допису
![image](https://cloud.githubusercontent.com/assets/5851581/20145402/aea4f9a8-a6a8-11e6-9d81-4c20914a4947.png)

- [x] Розділити окремо виведення звіту з рибалки і опису водойми.
ось як виглядає зараз звіт:
http://new.rivnefish.com/reports/533/Horyn--03-08-2016

ось як виглядає зараз опис водойми:
http://new.rivnefish.com/places/741/Horyn--s-Oleksandriia

- [x] Ось ці елементи: компаньйони, погода, рівень води і так далі пропоную замінити тими, які ми маємо в базі даних до кожного звіту. 
Ось перелік: 
Рейтинг 
Місце риболовлі
Початок рибалки
Кінець рибалки
Тип рибалки
Риба яку було спіймано
Місце

Якщо треба в цьому списку щось додати, можемо обговорити. Особисто мені сподобалась ідея вказувати прикормку.
Користувач стомиться заповнювати так багато полів, вважаю, що цього має бути достатньо.

- [x] Коментарі у нас зараз зберігають в системі Disqus, ми зможемо їх так стильно виводити на нашому сайті?

- [x] На сторінці зі звітом потрібно передбачити місце для елементів лайкання цієї статті. Користувачі будуть голосувати за контент, який їм подобається. На основі їх голосів ми будемо відбирати найкращі звіти, а їх авторам дарувати заохочувальні подарунки від наших спонсорів.

**Comment by Fesiuk** [comment]
"Якщо я кожного дня користуюсь ресурсом, кожного дня бачити кнопку "спробувати" мене буде напрягати. Думаю, що варто показувати мапу відразу."

Согласен, но лучше тогда переименовать кнопку или сделать по другому, типа "перейти на карту" или что то в таком духе...Я понимаю что карта основная фича, но когда сразу попадаешь на сайт где карта во весь экран то как то чуть стремно, хотелось бы предисловие какое то, внешний вид, эстетики... м?

**Comment by Fesiuk** [comment]
![main](https://cloud.githubusercontent.com/assets/23362021/20172558/47e4448a-a73e-11e6-85af-219ec4fca9a4.jpg)

Типа так.

**Comment by stal1n274** [comment]
This issue was moved to rivnefish/rivnefish_theme#1
