### ISSUE TITLE
API: Повертати список риби для конкретного маркера

### ISSUE THREAD

**Issue by lordmegamax** [rivnefish/rivnefish#8]
Наприклад  http://api.rivnefish.com/markers/29/.
Має бути як мінімум зображення і назва риби.

**Comment by devrivne** [comment]
не хчу добавляти)
Треба вказівку з вище тоді добавлю. Зараз це робиться в межах апі
http://api.rivnefish.com/markers-fishes/?marker=29
Це верне всі зв*язані записи з 'маркерс_фішес' де маркер=29
