### ISSUE TITLE
Перенести форум

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#86]
На превеликий жаль зі зміною адреси домену rivnefish.com нам доведеться тягнути за собою й форум:  rivnefish.com/forum

Для цього потрібно підняти PHP та базу даних MySQL, можливо вилізе й ще щось.

План Б: перемістити форум на власну адресу forum.rivnefish.com і лишити на існуючому хостінгу.

**Comment by ttp** [comment]
Fixed?

**Comment by stal1n274** [comment]
Verified
