### ISSUE TITLE
Рейтинг водойм

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#9]
Мова йде про рейтинг кльову і одночасно умов відпочинку на кожній водоймі. 
Користувачі можуть виставляти рейтинг кльову на даній водоймі на поточний час, навіть не пишучи звіту, бо написати звіт то треба вміти ще клавіатурою користуватись і граматику знати, тому звітів зовсім мало, **хоча купа народу їздить на рибалку**.

А от зайти і тицьнути на рейтинг може навіть лінивий. Можна також дати можливість ввести невеличкий коментар. Скажімо, на останніх рибалках кльову нема і писати нема про що. А от був би рейтинг, я б його виставив, навіть не пишучи звіту. А побачивши, що хтось гарно відловився, зрозумів би, що у мене просто руки не звідти ростуть :-)

Рейтинг пропоную, від 1 до 5. 

Головна вимога: користувач повинен мати можливість голосувати знову і знову. При цьому його оцінка має не змінюватись, а додаватись в рейтинг. Бо він на рибалку поїхав сьогодні і клювало на 4, а через три тижні кльов вже на 3: отже оцінка 3,5.

Коли будуть дані, ми зможемо форумувати звіти за неділю, за місяць, за рік, за весь час. Добре дати можливість перегляду його розшифровки, хто із користувачів, коли і який виставив по даній водоймі. Також непогано зберігати рейтинги і давати можливість дивитися графіки кльову по водоймі на протязі року чи іншого періоду, а ще прикольно порівняти кльов із минулорічним. 
Ось приклад як будується такий графік: http://www.maximonline.ru/top100/girl/103/
На маркер обов'язково вивести рейтинги кльову (поточні, тобто, середні за цей тиждень). Тоді з першого погляду відвідувачі можуть оцінити стан по кльову. Особливо це актуально для портативних пристроїв. Відповідно, кількість відвідувань зросте, так як інформація буде мінятися досить активно. 

Зберігати в базі це пропоную ось так:

id             | place_id    | user_id      | rating        | create_date | modify_date
------------ | ------------- | ------------- | ------------- | ------------- | -------------
1 | 357| 100| 5|1451556287 | 1451556287 
2 | 357| 100| 4|1451556288 | 1451556288
3 | 45| 51| 4|1451556289 | 1451556289 
4 | 102| 34| 3|1451556295 | 1451556295
5 | 357| 100| 5|1451556299 | 1451556299

Один і той же користувач не може поставити рейтинг для водойми раніше, ніж через 24 години після своєї попередньої оцінки.

Речі до обговорення:
1. Для початку ми навіть можемо дозволити ставити оцінки не авторизованим користувачам?
2. Шкала рейтингу: десятибальна, чотирьох бальна, п'яти бальна? Он IMDB дозволяє навіть ставити рейтинг з оцінкою "немає зірочки"

Буду радий будь-яким вашим ідеям та коментарям.

**Comment by ttp** [comment]
Перевір те, що є зараз, обговоримо офлайн

**Comment by stal1n274** [comment]
Ну, воно то робить, перевіряли з двох незалежних місць: http://new.rivnefish.com/places/tuchin
Але ще треба завтра перевірити чи дасть проголосувати.

Взагалі ця чудово фіча потребує подальшого обговорення :)
Те що є зараз — база, далі можна танцювати. Дякую!
