### ISSUE TITLE
Фотографії завантажуються неперевенрутими

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#97]
Приклад:
http://rivnefish.com/reports/2328/Babyn--05-04-2017 - друге фото в галереї

**Comment by ttp** [comment]
зазіпуй оригінальне фото і заатач сюди

**Comment by stal1n274** [comment]
Чомусь не дає прямо сюди приєднати мій ZIP архів.
Ось: https://drive.google.com/open?id=0B4ZbB6_dOxLCczdycWtmcUd0MFU

**Comment by ttp** [comment]
@stal1n274 потестуй

**Comment by stal1n274** [comment]
Все гарно, працює як треба
